# Generated by Django 3.1.6 on 2021-04-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='x_coordinate',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='y_coordinate',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
    ]
