# Generated by Django 3.1.6 on 2021-04-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210407_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thoughts',
            name='test',
        ),
        migrations.AddField(
            model_name='thoughts',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.location'),
            preserve_default=False,
        ),
    ]
