# Generated by Django 3.1.6 on 2021-04-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210408_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughts',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.location'),
        ),
    ]
