# Generated by Django 3.1.6 on 2021-04-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20210410_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(default=123, max_length=5000),
            preserve_default=False,
        ),
    ]
