# Generated by Django 3.1.6 on 2021-04-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_location_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='averageRating',
        ),
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
    ]
