# Generated by Django 3.1.6 on 2021-04-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20210410_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
