# Generated by Django 3.1.6 on 2021-04-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='firstname',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='lastname',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='studentID',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
