# Generated by Django 3.1.6 on 2021-04-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20210410_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='studentID',
        ),
    ]
