# Generated by Django 3.1.6 on 2021-04-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_remove_review_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='date published'),
        ),
    ]
