# Generated by Django 3.1.6 on 2021-05-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20210504_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
